### ISSUE TITLE
great examples

### ISSUE THREAD

**Issue by geraldstanje** [ricleal/PythonCode#1]
Hi,

Thanks for adding those examples: PythonCode/PyQt5/test_plot1d.py

Did you also plot a large dataset with > 500k samples using the 1d pot?
The plot does not open when i change plot1d as follows. any idea about that?

```
def plot1d():
    x_data = np.arange(0, 60000,1)
```

Is the plotting always accelerated by the GPU using webgl when using plotly.offline?

Thanks

**Comment by ricleal** [comment]
@geraldstanje : Sorry for the delay.
I don't know why I never got a notification for this...
I tried to play with the code and increase the number of samples and yes, it does display nothing :(
If you playing with large samples you could try `bokeh` rather than `plotly`. I know `Bokeh` has a WebGL backend:
http://bokeh.pydata.org/en/latest/docs/user_guide/webgl.html
Good luck!
